In [16]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,KFold,StratifiedKFold,LeaveOneOut,cross_val_score
from sklearn.metrics import accuracy_score

In [3]:
df=sns.load_dataset("iris")

In [4]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [12]:
x=df.drop(["species"],axis =1)
y=df[["species"]]

In [13]:
#holdout cross validation
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
model1=dt.fit(xtrain,ytrain)
model1.score(xtest,ytest)

1.0

In [15]:
#prediction
y_pred=model1.predict(xtest)
evaluation_score=accuracy_score(ytest,y_pred)
evaluation_score

1.0

In [19]:
#kfold cross validation
kfold=KFold(n_splits=6)

In [20]:
score=cross_val_score(dt,x,y,cv=kfold)
score

array([1.  , 1.  , 0.92, 0.92, 0.88, 0.88])

In [21]:
score.mean()

np.float64(0.9333333333333332)

In [22]:
#StratifiedKFold
StratifiedKFold=StratifiedKFold(n_splits=6)


In [23]:
scorE1=cross_val_score(dt,x,y,cv=StratifiedKFold)
scorE1


array([0.96, 1.  , 0.92, 0.92, 0.92, 1.  ])

In [24]:
scorE1.mean()

np.float64(0.9533333333333333)

In [25]:
#LeaveOneOut
LeaveOneOut=LeaveOneOut()

In [26]:
score2=cross_val_score(dt,x,y,cv=LeaveOneOut)
score2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
score2.mean()

np.float64(0.9533333333333334)